import type { Language } from "@/lib/i18n";

export type FlashcardLevel = "basic" | "advanced";

export type MathFlashcard = {
  id: string;
  unitId: string;
  level: FlashcardLevel;
  tag: Record<Language, string>;
  front: Record<Language, string>;
  back: Record<Language, string>;
  formula?: string;
  why: Record<Language, string>;
};

const b = (
  id: string,
  unitId: string,
  tagPl: string,
  tagEn: string,
  frontPl: string,
  frontEn: string,
  backPl: string,
  backEn: string,
  formula: string | undefined,
  whyPl: string,
  whyEn: string,
  level: FlashcardLevel = "basic",
): MathFlashcard => ({
  id,
  unitId,
  level,
  tag: { pl: tagPl, en: tagEn },
  front: { pl: frontPl, en: frontEn },
  back: { pl: backPl, en: backEn },
  formula,
  why: { pl: whyPl, en: whyEn },
});

export const mathFlashcards: MathFlashcard[] = [
  b("rn-powers","real-numbers","Potęgi","Powers","Co robisz z wykładnikami przy mnożeniu potęg o tej samej podstawie?","What happens to exponents when powers with the same base are multiplied?","Dodajesz wykładniki.","Add the exponents.","a^m\\cdot a^n=a^{m+n}","Podstawa zostaje ta sama, bo mnożysz kolejne czynniki tej samej liczby.","The base stays unchanged because you are multiplying more factors of the same number."),
  b("rn-roots","real-numbers","Pierwiastki","Roots","Jak uprościć pierwiastek z iloczynu dodatnich liczb?","How can you simplify the square root of a product of non-negative numbers?","Możesz rozdzielić pierwiastek na iloczyn pierwiastków.","Split the root into a product of roots.","\\sqrt{ab}=\\sqrt a\\sqrt b","To pozwala wyciągać pełne kwadraty spod pierwiastka.","This lets you extract perfect squares from under the radical."),
  b("rn-percent","real-numbers","Procenty","Percentages","Jak zapisać wzrost wartości o p procent jako mnożnik?","How do you express an increase by p percent as a multiplier?","Mnożysz przez 1 + p/100.","Multiply by 1 + p/100.","K_{nowe}=K_{stare}\\left(1+\\frac p{100}\\right)","Kolejna zmiana procentowa działa na aktualną, a nie początkową wartość.","Each later percentage change acts on the current value, not the original one."),
  b("rn-log","real-numbers","Logarytmy","Logarithms","Co dokładnie oznacza logarytm logₐ b = c?","What exactly does logₐ b = c mean?","Że a podniesione do potęgi c daje b.","It means a raised to c equals b.","\\log_a b=c\\iff a^c=b","Definicja logarytmu zamienia pytanie o wykładnik na równanie potęgowe.","The definition turns a question about an exponent into an exponential equation.","advanced"),

  b("alg-sum-square","algebra","Wzory skróconego mnożenia","Identities","Rozwiń kwadrat sumy.","Expand the square of a sum.","Kwadrat pierwszego, dwa razy iloczyn i kwadrat drugiego.","Square the first term, add twice the product, then square the second.","(a+b)^2=a^2+2ab+b^2","Najczęstszy błąd to pominięcie środkowego składnika 2ab.","The most common error is forgetting the middle term 2ab."),
  b("alg-diff-square","algebra","Wzory skróconego mnożenia","Identities","Rozwiń kwadrat różnicy.","Expand the square of a difference.","Środkowy składnik ma znak minus.","The middle term has a minus sign.","(a-b)^2=a^2-2ab+b^2","Minus dotyczy iloczynu 2ab, ale b² pozostaje dodatnie.","The minus affects 2ab, while b² remains positive."),
  b("alg-difference","algebra","Rozkład na czynniki","Factoring","Jak rozłożyć różnicę kwadratów?","How do you factor a difference of squares?","Na iloczyn sumy i różnicy.","As a product of a sum and a difference.","a^2-b^2=(a-b)(a+b)","To jeden z najszybszych sposobów skracania i rozwiązywania równań.","It is one of the fastest patterns for simplifying and solving equations."),
  b("alg-factor","algebra","Wielomiany","Polynomials","Co zwykle sprawdzasz przed użyciem bardziej skomplikowanej metody rozkładu wielomianu?","What should you usually check before using a more complicated factoring method?","Czy każdy składnik ma wspólny czynnik.","Whether all terms share a common factor.",undefined,"Wyłączenie wspólnego czynnika upraszcza wyrażenie i często odsłania dalszy wzór.","Factoring out a common factor simplifies the expression and often reveals another pattern.","advanced"),

  b("eq-linear","equations","Równanie liniowe","Linear equation","Jaki jest cel kolejnych przekształceń równania liniowego?","What is the goal of transformations in a linear equation?","Zostawić niewiadomą samą po jednej stronie.","Isolate the unknown on one side.","ax+b=c\\Rightarrow x=\\frac{c-b}{a}","Po obu stronach równania wykonujesz zawsze tę samą operację.","Every operation must be applied to both sides of the equation."),
  b("eq-delta","equations","Równanie kwadratowe","Quadratic equation","Po co liczymy deltę w równaniu kwadratowym?","Why do we calculate the discriminant in a quadratic equation?","Aby ustalić liczbę rzeczywistych pierwiastków i przygotować wzór na rozwiązania.","To determine the number of real roots and use the quadratic formula.","\\Delta=b^2-4ac","Znak delty mówi: dwa, jeden albo zero pierwiastków rzeczywistych.","The sign of the discriminant tells you whether there are two, one or no real roots."),
  b("eq-roots","equations","Równanie kwadratowe","Quadratic equation","Jak wygląda wzór na pierwiastki równania kwadratowego?","What is the quadratic formula?","Minus b plus lub minus pierwiastek z delty, wszystko przez 2a.","Negative b plus or minus the square root of the discriminant, all over 2a.","x_{1,2}=\\frac{-b\\pm\\sqrt\\Delta}{2a}","Warto pilnować nawiasu w liczniku i dzielenia całego licznika przez 2a.","Keep the whole numerator together before dividing by 2a."),
  b("eq-inequality","equations","Nierówności","Inequalities","Kiedy odwracasz znak nierówności?","When do you reverse an inequality sign?","Gdy mnożysz lub dzielisz obie strony przez liczbę ujemną.","When multiplying or dividing both sides by a negative number.","-2x>6\\Rightarrow x<-3","To nie jest kosmetyka: bez zmiany znaku zbiór rozwiązań byłby przeciwny.","This is essential; otherwise you obtain the opposite solution set.","advanced"),

  b("sys-sub","systems","Podstawianie","Substitution","Na czym polega metoda podstawiania w układzie równań?","What is substitution in a system of equations?","Wyznaczasz jedną niewiadomą z jednego równania i wstawiasz ją do drugiego.","Solve one equation for one variable and substitute it into the other.",undefined,"Sprowadzasz układ dwóch niewiadomych do jednego równania z jedną niewiadomą.","It reduces a two-variable system to one equation in one variable."),
  b("sys-elim","systems","Eliminacja","Elimination","Jaki jest cel metody przeciwnych współczynników?","What is the goal of elimination?","Doprowadzić do zniknięcia jednej niewiadomej po dodaniu lub odjęciu równań.","Make one variable cancel when the equations are added or subtracted.",undefined,"Czasem trzeba najpierw pomnożyć jedno lub oba równania przez odpowiednie liczby.","You may first need to multiply one or both equations by suitable constants."),
  b("sys-geometry","systems","Interpretacja","Interpretation","Co oznacza jedno rozwiązanie układu dwóch równań liniowych na wykresie?","What does one solution of two linear equations mean graphically?","Proste przecinają się dokładnie w jednym punkcie.","The lines intersect at exactly one point.",undefined,"Współrzędne punktu przecięcia spełniają jednocześnie oba równania.","The intersection coordinates satisfy both equations at the same time."),
  b("sys-model","systems","Zadania tekstowe","Word problems","Od czego zacząć układ równań w zadaniu tekstowym?","How should you start modelling a word problem with a system?","Nazwać niewiadome i zapisać dwie niezależne zależności z treści.","Name the unknowns and write two independent relationships from the text.",undefined,"Bez dwóch niezależnych warunków zwykle nie da się jednoznacznie wyznaczyć dwóch niewiadomych.","Two unknowns usually require two independent conditions.","advanced"),

  b("fun-slope","functions","Funkcja liniowa","Linear function","Co mówi współczynnik a we wzorze f(x)=ax+b?","What does a mean in f(x)=ax+b?","O ile zmienia się wartość funkcji, gdy x rośnie o 1.","How much the function value changes when x increases by 1.","f(x)=ax+b","Dodatnie a oznacza funkcję rosnącą, ujemne — malejącą.","Positive a gives an increasing function; negative a gives a decreasing one."),
  b("fun-zero","functions","Miejsce zerowe","Zero","Jak znaleźć miejsce zerowe funkcji liniowej?","How do you find the zero of a linear function?","Podstawiasz f(x)=0 i rozwiązujesz równanie.","Set f(x)=0 and solve.","ax+b=0\\Rightarrow x=-\\frac ba","Miejsce zerowe to współrzędna x punktu przecięcia wykresu z osią OX.","The zero is the x-coordinate where the graph crosses the x-axis."),
  b("fun-vertex","functions","Funkcja kwadratowa","Quadratic function","Co odczytasz natychmiast z postaci kanonicznej a(x−p)²+q?","What can you read immediately from a(x−p)²+q?","Wierzchołek paraboli ma współrzędne (p,q).","The parabola has vertex (p,q).","f(x)=a(x-p)^2+q","Znak a mówi dodatkowo, czy ramiona są skierowane w górę czy w dół.","The sign of a also tells whether the parabola opens up or down."),
  b("fun-shift","functions","Przekształcenia wykresu","Graph transformations","Co robi zapis f(x−p)+q z wykresem funkcji?","What does f(x−p)+q do to a graph?","Przesuwa wykres o p w prawo i q w górę.","It shifts the graph p units right and q units up.","y=f(x-p)+q","Znak przy p działa przeciwnie do intuicji, bo zmiana jest wewnątrz argumentu.","The horizontal sign feels reversed because the change happens inside the input.","advanced"),

  b("seq-arith","sequences","Ciąg arytmetyczny","Arithmetic sequence","Jak obliczyć n-ty wyraz ciągu arytmetycznego?","How do you find the nth term of an arithmetic sequence?","Dodajesz do pierwszego wyrazu n−1 razy różnicę.","Add the common difference n−1 times to the first term.","a_n=a_1+(n-1)r","Między a₁ i aₙ jest dokładnie n−1 kroków.","There are exactly n−1 steps from a₁ to aₙ."),
  b("seq-arith-sum","sequences","Suma ciągu","Sequence sum","Jak policzyć sumę pierwszych n wyrazów ciągu arytmetycznego?","How do you sum the first n terms of an arithmetic sequence?","Liczbę wyrazów mnożysz przez średnią pierwszego i ostatniego.","Multiply the number of terms by the average of the first and last.","S_n=\\frac{n(a_1+a_n)}2","Pierwszy z ostatnim, drugi z przedostatnim itd. tworzą pary o tej samej sumie.","First+last, second+penultimate and so on create equal-sum pairs."),
  b("seq-geom","sequences","Ciąg geometryczny","Geometric sequence","Jak obliczyć n-ty wyraz ciągu geometrycznego?","How do you find the nth term of a geometric sequence?","Mnożysz pierwszy wyraz przez q do potęgi n−1.","Multiply the first term by q to the power n−1.","a_n=a_1q^{n-1}","Każdy kolejny krok mnoży wartość przez ten sam iloraz q.","Each step multiplies the value by the same common ratio q."),
  b("seq-geom-sum","sequences","Suma ciągu","Sequence sum","Jaki wzór stosujesz do sumy n wyrazów ciągu geometrycznego dla q≠1?","Which formula gives the sum of n geometric terms for q≠1?","Używasz ilorazu różnicy potęg przez 1−q.","Use the geometric sum formula.","S_n=a_1\\frac{1-q^n}{1-q}","Forma z 1−q lub q−1 jest równoważna, jeśli konsekwentnie zmienisz licznik i mianownik.","Forms using 1−q or q−1 are equivalent if numerator and denominator are changed consistently.","advanced"),

  b("trig-sin","trigonometry","Trójkąt prostokątny","Right triangle","Czym jest sinus kąta ostrego w trójkącie prostokątnym?","What is the sine of an acute angle in a right triangle?","Stosunkiem przyprostokątnej naprzeciw kąta do przeciwprostokątnej.","Opposite leg divided by the hypotenuse.","\\sin\\alpha=\\frac{przeciwległa}{przeciwprostokątna}","Sinus łączy kąt z proporcją długości boków.","Sine links an angle to a ratio of side lengths."),
  b("trig-cos","trigonometry","Trójkąt prostokątny","Right triangle","Czym jest cosinus kąta ostrego?","What is the cosine of an acute angle?","Stosunkiem przyprostokątnej przy kącie do przeciwprostokątnej.","Adjacent leg divided by the hypotenuse.","\\cos\\alpha=\\frac{przyległa}{przeciwprostokątna}","Sinus i cosinus pozwalają przechodzić między bokami i kątami.","Sine and cosine let you move between sides and angles."),
  b("trig-id","trigonometry","Tożsamości","Identities","Jaka podstawowa tożsamość łączy sinus i cosinus tego samego kąta?","Which basic identity links sine and cosine of the same angle?","Suma ich kwadratów wynosi 1.","The sum of their squares is 1.","\\sin^2\\alpha+\\cos^2\\alpha=1","Pozwala wyznaczyć jedną funkcję trygonometryczną, gdy znasz drugą i znak.","It lets you find one trig value from the other, with the correct sign."),
  b("trig-cosrule","trigonometry","Twierdzenie cosinusów","Cosine rule","Kiedy twierdzenie cosinusów jest szczególnie użyteczne?","When is the cosine rule especially useful?","Gdy znasz dwa boki i kąt między nimi albo wszystkie trzy boki.","When you know two sides and the included angle, or all three sides.","c^2=a^2+b^2-2ab\\cos\\gamma","To uogólnienie twierdzenia Pitagorasa na dowolny trójkąt.","It generalises Pythagoras to any triangle.","advanced"),

  b("geo-triangle-area","planimetry","Pole trójkąta","Triangle area","Jak policzyć pole trójkąta z podstawy i wysokości?","How do you calculate triangle area from base and height?","Połowa iloczynu podstawy i odpowiadającej jej wysokości.","Half the product of a base and its corresponding height.","P=\\frac{ah}{2}","Wysokość musi być prostopadła do wybranej podstawy.","The height must be perpendicular to the chosen base."),
  b("geo-pyth","planimetry","Twierdzenie Pitagorasa","Pythagoras","Jaka zależność zachodzi w trójkącie prostokątnym?","What relation holds in a right triangle?","Kwadrat przeciwprostokątnej to suma kwadratów przyprostokątnych.","The square of the hypotenuse equals the sum of squares of the legs.","a^2+b^2=c^2","Przeciwprostokątna leży zawsze naprzeciw kąta prostego.","The hypotenuse is always opposite the right angle."),
  b("geo-circle","planimetry","Okrąg i koło","Circle","Jakie są wzory na obwód okręgu i pole koła?","What are the circumference and area formulas for a circle?","Obwód 2πr, pole πr².","Circumference 2πr, area πr².","L=2\\pi r,\\qquad P=\\pi r^2","Promień w polu jest podniesiony do kwadratu, bo pole ma jednostki kwadratowe.","The radius is squared in area because area uses square units."),
  b("geo-similarity","planimetry","Podobieństwo","Similarity","Jak skala podobieństwa k wpływa na pola figur?","How does similarity scale k affect areas?","Pola zmieniają się w skali k².","Areas scale by k².","\\frac{P_2}{P_1}=k^2","Długości są jednowymiarowe, pola dwuwymiarowe, dlatego pojawia się kwadrat skali.","Lengths are one-dimensional and areas two-dimensional, hence k².","advanced"),

  b("ag-slope","analytic-geometry","Prosta","Line","Jak policzyć współczynnik kierunkowy prostej przez dwa punkty?","How do you find the slope through two points?","Różnica y podzielona przez różnicę x.","Change in y divided by change in x.","a=\\frac{y_2-y_1}{x_2-x_1}","Mianownik nie może być zerem — pionowa prosta nie ma skończonego współczynnika kierunkowego.","The denominator cannot be zero; a vertical line has no finite slope."),
  b("ag-distance","analytic-geometry","Odległość","Distance","Jak policzyć odległość dwóch punktów w układzie współrzędnych?","How do you find the distance between two coordinate points?","Z twierdzenia Pitagorasa dla różnic współrzędnych.","Use Pythagoras on the coordinate differences.","d=\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}","Różnice współrzędnych są przyprostokątnymi niewidocznego trójkąta prostokątnego.","Coordinate differences form the legs of an implicit right triangle."),
  b("ag-midpoint","analytic-geometry","Środek odcinka","Midpoint","Jak znaleźć środek odcinka AB?","How do you find the midpoint of AB?","Uśredniasz osobno współrzędne x i y.","Average the x-coordinates and y-coordinates separately.","S=\\left(\\frac{x_A+x_B}{2},\\frac{y_A+y_B}{2}\\right)","Środek leży dokładnie w połowie drogi w obu osiach.","The midpoint lies halfway along both coordinate directions."),
  b("ag-circle","analytic-geometry","Okrąg","Circle","Co odczytasz z równania (x−a)²+(y−b)²=r²?","What can you read from (x−a)²+(y−b)²=r²?","Środek S=(a,b) i promień r.","Centre S=(a,b) and radius r.","(x-a)^2+(y-b)^2=r^2","Równanie mówi, że każdy punkt okręgu ma tę samą odległość r od środka.","Every point on the circle is exactly distance r from the centre.","advanced"),

  b("st-prism","stereometry","Graniastosłup","Prism","Jak obliczyć objętość graniastosłupa?","How do you calculate the volume of a prism?","Pole podstawy razy wysokość.","Base area times height.","V=P_p\\cdot H","Każdy przekrój równoległy do podstawy ma to samo pole.","Every cross-section parallel to the base has the same area."),
  b("st-pyramid","stereometry","Ostrosłup","Pyramid","Jak obliczyć objętość ostrosłupa?","How do you calculate the volume of a pyramid?","Jedna trzecia pola podstawy razy wysokość.","One third of base area times height.","V=\\frac13P_pH","Ostrosłup o tej samej podstawie i wysokości ma 1/3 objętości odpowiedniego graniastosłupa.","A pyramid with the same base and height has one third the prism volume."),
  b("st-cylinder","stereometry","Walec","Cylinder","Jak obliczyć objętość walca?","How do you calculate cylinder volume?","Pole koła w podstawie razy wysokość.","Area of the circular base times height.","V=\\pi r^2H","Walec jest szczególnym przypadkiem bryły o stałym przekroju.","A cylinder is a solid with a constant cross-sectional area."),
  b("st-sphere","stereometry","Kula","Sphere","Jak zmiana promienia dwa razy wpływa na objętość kuli?","What happens to sphere volume if the radius doubles?","Objętość rośnie osiem razy.","The volume becomes eight times larger.","V=\\frac43\\pi r^3","Objętość skaluje się z trzecią potęgą długości.","Volume scales with the cube of a length.","advanced"),

  b("comb-factorial","combinatorics","Permutacje","Permutations","Ile ustawień ma n różnych elementów w kolejności?","How many orderings are there for n distinct elements?","n silnia.","n factorial.","P_n=n!","Na pierwsze miejsce masz n wyborów, na kolejne n−1 itd.","There are n choices first, then n−1, and so on."),
  b("comb-combination","combinatorics","Kombinacje","Combinations","Kiedy używasz symbolu Newtona n po k?","When do you use n choose k?","Gdy wybierasz k elementów z n i kolejność nie ma znaczenia.","When choosing k elements from n and order does not matter.","\\binom nk=\\frac{n!}{k!(n-k)!}","Dzielenie przez k! usuwa wielokrotne policzenie tych samych grup w różnych kolejnościach.","Dividing by k! removes different orders of the same chosen group."),
  b("comb-variation","combinatorics","Wariacje","Variations","Ile jest uporządkowanych wyborów k różnych elementów z n bez powtórzeń?","How many ordered selections of k distinct elements from n are possible without repetition?","n!/(n−k)!.","n!/(n−k)!.","V_n^k=\\frac{n!}{(n-k)!}","Kolejność ma znaczenie, ale elementu nie można użyć ponownie.","Order matters, but an element cannot be reused."),
  b("comb-product","combinatorics","Reguła mnożenia","Multiplication principle","Jeśli pierwszy etap ma a możliwości, a drugi b, ile jest wszystkich par decyzji?","If one stage has a choices and the next b, how many combined outcomes are there?","a·b.","a·b.","N=a\\cdot b","Niezależne kolejne wybory mnożysz, alternatywne rozłączne przypadki dodajesz.","Multiply sequential independent choices; add disjoint alternatives.","advanced"),

  b("prob-classic","probability","Prawdopodobieństwo","Probability","Jaki jest klasyczny wzór na prawdopodobieństwo zdarzenia A?","What is the classical probability formula for event A?","Liczba wyników sprzyjających przez liczbę wszystkich jednakowo możliwych wyników.","Favourable outcomes divided by all equally likely outcomes.","P(A)=\\frac{|A|}{|\\Omega|}","Wzór wymaga modelu, w którym wyniki elementarne są jednakowo prawdopodobne.","The formula assumes elementary outcomes are equally likely."),
  b("prob-complement","probability","Zdarzenie przeciwne","Complement","Jak policzyć prawdopodobieństwo zdarzenia przeciwnego?","How do you find the probability of the complement?","Od 1 odejmujesz prawdopodobieństwo zdarzenia.","Subtract the event probability from 1.","P(A')=1-P(A)","Często łatwiej policzyć „co najmniej jedno” przez odjęcie przypadku „ani jednego”.","It is often easier to calculate “at least one” via the complement “none”."),
  b("prob-independent","probability","Niezależność","Independence","Jak liczysz prawdopodobieństwo jednoczesnego zajścia dwóch niezależnych zdarzeń?","How do you find the probability that two independent events both occur?","Mnożysz ich prawdopodobieństwa.","Multiply their probabilities.","P(A\\cap B)=P(A)P(B)","Niezależność oznacza, że informacja o jednym zdarzeniu nie zmienia szans drugiego.","Independence means knowing one event occurred does not change the other probability."),
  b("prob-conditional","probability","Warunkowe","Conditional probability","Co oznacza P(A|B)?","What does P(A|B) mean?","Prawdopodobieństwo A przy założeniu, że B już zaszło.","Probability of A given that B has already occurred.","P(A|B)=\\frac{P(A\\cap B)}{P(B)}","Po informacji B zawężasz przestrzeń możliwych wyników do przypadków zgodnych z B.","Once B is known, the sample space is restricted to outcomes compatible with B.","advanced"),

  b("calc-power","calculus","Pochodna","Derivative","Jaka jest pochodna xⁿ?","What is the derivative of xⁿ?","n·xⁿ⁻¹.","n·xⁿ⁻¹.","(x^n)'=nx^{n-1}","Wykładnik schodzi przed potęgę i zmniejsza się o 1.","The exponent moves in front and decreases by one."),
  b("calc-tangent","calculus","Styczna","Tangent","Jak interpretujesz wartość f′(x₀) geometrycznie?","What is the geometric meaning of f′(x₀)?","To współczynnik kierunkowy stycznej do wykresu w x₀.","It is the slope of the tangent to the graph at x₀.","a_{stycznej}=f'(x_0)","Pochodna opisuje lokalne tempo zmiany funkcji.","The derivative describes the local rate of change."),
  b("calc-monotonic","calculus","Monotoniczność","Monotonicity","Co zwykle oznacza f′(x)>0 na przedziale?","What does f′(x)>0 usually imply on an interval?","Funkcja jest tam rosnąca.","The function is increasing there.","f'(x)>0\\Rightarrow f\\;\\text{rośnie}","Znak pochodnej mówi o kierunku lokalnej zmiany funkcji.","The derivative sign indicates the direction of local change."),
  b("calc-opt","calculus","Optymalizacja","Optimisation","Jaki jest typowy schemat zadania optymalizacyjnego z pochodną?","What is a typical derivative-based optimisation workflow?","Zbuduj funkcję celu, wyznacz dziedzinę, policz pochodną, znajdź punkty krytyczne i porównaj wartości.","Build the objective function, determine the domain, differentiate, find critical points and compare values.",undefined,"Samo rozwiązanie f′(x)=0 nie wystarcza — trzeba sprawdzić, czy znaleziony punkt rzeczywiście daje maksimum lub minimum.","Solving f′(x)=0 alone is not enough; verify that the point truly gives the required maximum or minimum.","advanced"),
];

export function flashcardCounts() {
  return {
    basic: mathFlashcards.filter((card) => card.level === "basic").length,
    advanced: mathFlashcards.filter((card) => card.level === "advanced").length,
    total: mathFlashcards.length,
  };
}
